### ISSUE TITLE
Test/Build Pipeline

### ISSUE THREAD

**Issue by thatsIch** [snaketron/BcellNet#1]
@snaketron I am currently implementing a test/build pipeline for this project. The problem is, that this is a personal repository, we can not use build tools like travis-ci and build tools like circle-ci which support contributor repositories do not support R.

Possible solutions would be:

1. ignore testing
2. move to organisation instead of personal repository
3. you setup the initial settings in travis

I personally would prefer 2. but maybe there are personal/internal reasons not to.

**Comment by snaketron** [comment]
Unfortunately, 2. would be difficult but 3. sounds ok.

**Comment by thatsIch** [comment]
I think it works now. It seems Travis just took longer to register, that I am also a contributor to change the settings, thus 3. is not needed anymore.

**Comment by snaketron** [comment]
Great!
