### ISSUE TITLE
perhaps a bug?

### ISSUE THREAD

**Issue by snaketron** [snaketron/BcellNet#11]
matrixSecond <- matrices[[1]]
matrixFirst <- matrices[[2]]

**Comment by GitCJW** [comment]
No, thats right.

**Comment by snaketron** [comment]
Have you tried testing your program with samples which do not contain equal number of positive and negative patient sequences?

**Comment by GitCJW** [comment]
We did and everthing was fine. Thtas a new bug, thanks!
