### ISSUE TITLE
Clear graphs after another plot

### ISSUE THREAD

**Issue by GitCJW** [snaketron/BcellNet#19]

**Comment by thatsIch** [comment]
What do you mean with clear graphs?

**Comment by GitCJW** [comment]
When you plot a graph only for the first patient (due to vj-segment) and after that plot another graph (based on another subset or vj-segment etc..) for the second patient, the graph plotted before will be present. 
So, to avoid this, clear the graph / plots before running a new plot

**Comment by thatsIch** [comment]
Does comparing patients on different VJ-segments make sense?

**Comment by thatsIch** [comment]
@snaketron 

> Does comparing patients on different VJ-segments make sense?

**Comment by snaketron** [comment]
@thatsIch I do not think that makes much sense. Comparing clonal expansion in different V-J segments of a single patient might be interesting though.
