### ISSUE TITLE
Create graph for BCRs

### ISSUE THREAD

**Issue by GitCJW** [snaketron/BcellNet#3]
Implement a function which create a graph based on a given set of bcrs and its distances.
Nodes represent the bcrs (include the sequence) and edges similarity of two connected nodes. The edge contain the value of distance/similarity.

**Comment by thatsIch** [comment]
Input: 

* Patient Name
* IGraph Data with all vertices as entry and their distance as edge weight
* Edge weight level to hide edges with low weight correlation
* Color of vertices

Process:

* The weight is normalized where 0 is better and higher is worse
* Layout by weight e.g. using `layout_with_fr`
* Detect communities

**Comment by thatsIch** [comment]
Color can be interpolated via defaults if given two datasets

**Comment by thatsIch** [comment]
@snaketron About how many vertices can a live dataset contain? This is about scaling the graph to consider different plotting techniques due to size (e.g. if there are so many data entries you might only get one big pile of colored circles)

**Comment by snaketron** [comment]
@thatsIch Difficult to say. Probably dozens of hub vertices (unique sequences with high occurrence in the dataset) and perhaps hundreds of vertices around each hub.

Was this helpful?

**Comment by thatsIch** [comment]
@snaketron Yes, thank you very much.

**Comment by thatsIch** [comment]
![rplot](https://cloud.githubusercontent.com/assets/2210496/22073913/f27d9c86-dda6-11e6-9ed4-b4a5450f680a.png)

potential plot
