### ISSUE TITLE
Create simple GUI

### ISSUE THREAD

**Issue by GitCJW** [snaketron/BcellNet#4]
The first version of the GUI should contain some basic elements like frames for showing the (two) graphs, some buttons/drop down menus, slider etc.

**Comment by thatsIch** [comment]
@BehnazSpieker maybe take a look at https://shiny.rstudio.com/ this uses an mini application server to render HTML5. It also provides examples with interactivity. This is also supported in RStudio and standalone.

**Comment by BehnazSpieker** [comment]
Thanks. Actually I prepare some GUI, but I also take a look at the shiny.😊

**Comment by BehnazSpieker** [comment]
gute Empfehlung, es hat mehr als anderen libraries Spaß gemacht , danke dir
